### PR TITLE
Unsuccessful delete/rollback means the test is still on system.

### PR DESCRIPTION
**Pull request by trapnine**
Also, a 404 on TDS delete means the delete succeeded (test not there).

### CODE REVIEW

**Comment by trapnine** [comment]
A 404 on TDS delete now means the delete succeeded (test not there) - should we adopt this for the other systems as well? Not sure if they will give a 404 if and only if the exam is not there (and therefore, already 'deleted').

Obviously this would only behave this way for a confirmed 404 response - any other communications error still results in a filed delete (meaning it will still show up as present!!).

**Comment by burzum619** [comment]
If the system is not accessible or the host name is changed and is now incorrect, wouldn't that too return a 400? In that case the test package would still remain in a loaded state on the external system.

**Comment by trapnine** [comment]
Well, you'd only get a 404 if the service was up, responding, authorized, and then couldn't find what you requested.

**Comment by burzum619** [comment]
In that case, LGTM

**Pull request merged**
